//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coddee tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Coddee;
using Coddee.Data.REST;
using HR.Data.Models;
using HR.Data.Repositories;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace HR.Data.Rest.Repositories
{

    [Coddee.Data.RepositoryAttribute(typeof(IBranchRepository))]
    public class BranchRepository : CRUDRESTRepositoryBase<Branch, int>, IBranchRepository
    {
        public BranchRepository() :
                base("Branch")
        {
        }

        public Task<IEnumerable<Branch>> GetItemsWithDetails()
        {
            return GetFromController<IEnumerable<Branch>>();
        }

        public Task<IEnumerable<Branch>> GetItemsWithDetailsByCompany(int companyId)
        {
            return GetFromController<IEnumerable<Branch>>(new Dictionary<string, string>
            {
                {nameof(companyId),companyId.ToString() },
            });
        }
    }
}
