//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coddee tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Coddee;
using Coddee.Data.REST;
using HR.Data.Models;
using HR.Data.Repositories;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace HR.Data.Rest.Repositories
{
    
    [Coddee.Data.RepositoryAttribute(typeof(ICompanyRepository))]
    public class CompanyRepository : CRUDRESTRepositoryBase<Company, int>, ICompanyRepository
    {
        public CompanyRepository() : 
                base("Company")
        {
        }

        public Task<IEnumerable<Company>> GetItemsWithDetails()
        {
            return GetFromController<IEnumerable<Company>>();
        }
    }
}
