//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coddee tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Coddee;
using Coddee.Data.REST;
using HR.Data.Models;
using HR.Data.Repositories;
using System;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Coddee.Security;

namespace HR.Data.Rest.Repositories
{

    [Coddee.Data.RepositoryAttribute(typeof(IUserRepository))]
    public class UserRepository : CRUDRESTRepositoryBase<User, int>, IUserRepository
    {
        public UserRepository() :
                base("User")
        {
        }

        public Task CreateUser(User user, string password)
        {
            return PostToController(nameof(CreateUser),
                        new
                        {
                            User = user,
                            Password = password
                        });
        }

        public async Task<HRAuthenticationResponse> AuthenticationUser(string username, string password)
        {
            var res = await PostToController<HRAuthenticationResponse>(nameof(AuthenticationUser),
                                                           new { Username = username, Password = password });
            if (res.Status == AuthenticationStatus.Successfull)
            {
                _httpClient.DefaultRequestHeaders.Authorization =AuthenticationHeaderValue.Parse($"Bearer {res.AuthenticationToken}");
            }
            return res;
        }
    }
}
