-- Copyright (c) Aghyad khlefawi. All rights reserved.  
-- Licensed under the MIT License. See LICENSE file in the project root for full license information.

Create TABLE [dbo].States(
ID INT PRIMARY KEY IDENTITY,
Name NVARCHAR(50) NOT NULL,
Code NVARCHAR(4) NOT NULL);

CREATE TABLE [dbo].Companies(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWSEQUENTIALID()),
Name NVARCHAR(200) NOT NULL,
StateID INT NOT NULL FOREIGN KEY REFERENCES dbo.States(ID));

CREATE TABLE [dbo].Employees(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWSEQUENTIALID()),
FirstName NVARCHAR(200) NOT NULL,
LastName NVARCHAR(200) NOT NULL,
CompanyID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.Companies(ID));


CREATE TABLE [dbo].Users(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWSEQUENTIALID()),
Username NVARCHAR(200) NOT NULL,
PasswordHash NVARCHAR(200) NOT NULL,
PasswordSalt NVARCHAR(200) NOT NULL);
