//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coddee tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Coddee;
using HR.Data.Models;
using HR.Data.Repositories;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace HR.Data.Linq.Repositories
{

    [Coddee.Data.RepositoryAttribute(typeof(ICompanyRepository))]
    public class CompanyRepository : CRUDHRRepositoryBase<DB.Company, Company, int>, ICompanyRepository
    {
        public override void RegisterMappings(IObjectMapper mapper)
        {
            base.RegisterMappings(mapper);
            mapper.RegisterMap<DB.CompaniesView,Company>();
        }

        public Task<IEnumerable<Company>> GetItemsWithDetails()
        {
            return ExecuteAndMapCollection(db => db.CompaniesViews.ToList());
        }
    }
}
