//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coddee tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Coddee;
using Coddee.Data;
using HR.Data.Models;
using HR.Data.Repositories;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Coddee.Crypto;
using Coddee.Security;
using System.Linq;

namespace HR.Data.Linq.Repositories
{

    [Coddee.Data.RepositoryAttribute(typeof(IUserRepository))]
    public class UserRepository : CRUDHRRepositoryBase<DB.User, User, int>, IUserRepository
    {
        public Task<HRAuthenticationResponse> AuthenticationUser(string username, string password)
        {
            return Execute((db, table) =>
            {
                try
                {
                    username = username.ToLower();
                    var user = table.FirstOrDefault(e => e.Username.ToLower() == username);
                    if (user == null || !PasswordHelper.ValidatePassword(password, user.PasswordSalt, user.PasswordHash))
                        return new HRAuthenticationResponse
                        {
                            Status = AuthenticationStatus.InvalidCredentials
                        };
                    return new HRAuthenticationResponse
                    {
                        Status = AuthenticationStatus.Successfull,
                        Username = user.Username
                    };
                }
                catch (Exception e)
                {
                    return new HRAuthenticationResponse
                    {
                        Error = e.Message,
                        Status = AuthenticationStatus.Failed
                    };
                }
            });
        }

        public Task CreateUser(User user, string password)
        {
            return Execute((db, table) =>
            {
                var dbUser = _mapper.Map<DB.User>(user);
                var pass = PasswordHelper.GenerateHashedPassword(password);
                dbUser.PasswordHash = pass.Password;
                dbUser.PasswordSalt = pass.Salt;

                table.InsertOnSubmit(dbUser);
            });
        }
    }
}
