//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coddee tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Coddee;
using Coddee.Data;
using HR.Data.Models;
using HR.Data.Repositories;
using System;
using Coddee.Data;

namespace HR.Data.Rest.Repositories
{
    
    [Coddee.Data.RepositoryAttribute(typeof(IJobRepository))]
    public class JobRepository : CRUDFileRepositoryBase<Job, int>, IJobRepository
    {
        public JobRepository() : 
                base("Job")
        {
        }
    }
}
