//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coddee tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Coddee;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace HR.Data.Models
{
   
    public class Branch : IUniqueObject<int>, IEquatable<IUniqueObject<int>>, IEquatable<Branch>
    {
        
        public System.Int32 Id { get; set; }
        public System.String Name { get; set; }
        public System.Int32 CompanyId { get; set; }
        public System.Int32 CityId { get; set; }

        public List<Employee> Employees { get; set; }

        [IgnoreDataMember]
        public System.Int32 GetKey => Id;

        public int CountryId { get; set; }

        public string CompanyName { get; set; }
        public string CountryName { get; set; }
        public string CityName { get; set; }
        public int EmployeeCount { get; set; }

        public override bool Equals(object obj)
        {
            var other = obj as IUniqueObject<System.Int32>;
            if (other != null)
            {
                return this.Equals(other);
            }
            else
            {
                return base.Equals(obj);
            }
        }
        public override int GetHashCode()
        {
            return this.GetKey.GetHashCode();
        }
        public virtual bool Equals(IUniqueObject<int> other)
        {
            if (((this.GetKey != -1)
                        && (other.GetKey != -1)))
            {
                return (this.GetKey == other.GetKey);
            }
            else
            {
                return object.ReferenceEquals(this, other);
            }
        }
        public virtual bool Equals(Branch other)
        {
            if (((this.GetKey != -1)
                        && (other.GetKey != -1)))
            {
                return (this.GetKey == other.GetKey);
            }
            else
            {
                return object.ReferenceEquals(this, other);
            }
        }
    }
}
